[package]
name = "pimalaya-config"
description = "Config utils for Pimalaya"
version = "0.1.4"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.89"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["config"]
keywords = ["pimalaya", "config", "toml", "secret"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/pimalaya-config/latest/pimalaya_config"
repository = "https://github.com/pimalaya/config"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["toml", "secret", "notify"]
notify = ["dep:notify-rust", "notify-rust/d"]
secret = ["dep:secrecy", "dep:thiserror"]
toml = ["dep:anyhow", "dep:dirs", "dep:log", "dep:shellexpand", "dep:toml"]
vendored = ["notify-rust?/d_vendored"]

[dependencies]
anyhow = { version = "1", default-features = false, features = ["std"], optional = true }
dirs = { version = "6.0", default-features = false, optional = true }
log = { version = "0.4", default-features = false, optional = true }
notify-rust = { version = "4", default-features = false, optional = true }
secrecy = { version = "0.10", default-features = false, features = ["serde"], optional = true }
serde = { version = "1", default-features = false, features = ["derive", "std"] }
shellexpand = { version = "3.1", default-features = false, features = ["base-0", "tilde"], optional = true }
thiserror = { version = "2", default-features = false, features = ["std"], optional = true }
toml = { version = "1.1", default-features = false, features = ["std", "parse", "display", "serde"], optional = true }
